version: "3"

services:
  smtp:
    image: kbedel/fake-smtp-server
    ports:
      - 1080:1080
      - 1025:1025
  mysql:
    image: mysql:8.0.26
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=app
      - MYSQL_ROOT_PASSWORD=app
    volumes:
      - my-datavolume:/var/lib/mysql
  redis:
    image: redis:6.0.9-alpine3.12
    ports:
      - 6379:6379
    volumes:
      - ./../data/redis:/data

volumes:
  my-datavolume: