version: "3"

services:
  smtp:
    image: kbedel/fake-smtp-server
    ports:
      - 1080:1080
      - 1025:1025
  neo4j:
    image: neo4j:4.0.3
    hostname: neo4j
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j-datavolume:/data
    environment:
      NEO4J_AUTH: neo4j/test
      NEO4J_dbms_logs_debug_level: DEBUG
  mysql:
    image: mysql:8.0.26
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=app
      - MYSQL_ROOT_PASSWORD=app
    volumes:
      - my-datavolume:/var/lib/mysql
  redis:
    image: redis:6.0.9-alpine3.12
    ports:
      - 6379:6379
    volumes:
      - redis-datavolume:/data

volumes:
  my-datavolume:
  neo4j-datavolume:
  redis-datavolume: