version: '3.8'

services:
  smtp:
    image: kbedel/fake-smtp-server
    networks:
      - default
  app:
    image: $APP_IMAGE
    environment:
      NODE_ENV: development
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USERNAME: app
      MYSQL_PASSWORD: app
      MYSQL_DATABASE: app
      REDIS_HOST: redis
      NEO4J_DATABASE: neo4j
      NEO4J_USERNAME: neo4j
      NEO4J_PASSWORD: test
      NEO4J_HOST: neo4j
      NEO4J_PORT: 7687
      NEO4J_PROTOCOL: neo4j
      NEO4J_ENCRYPTION: ENCRYPTION_OFF
    command: sh -c "npx nestjs-command db:wait && npx ts-node -r tsconfig-paths/register ./node_modules/typeorm/cli.js "migration:run" --config "ormconfigremote.json" && npm run test"
    networks:
      - default
  redis:
    image: redis:6.0.9-alpine3.12
    networks:
      - default
  neo4j:
    image: neo4j:4.0.3
    hostname: neo4j
    container_name: neo4j
    environment:
      NEO4J_AUTH: neo4j/test
      NEO4J_dbms_logs_debug_level: DEBUG
  mysql:
    image: mysql:8.0.22
    command: --default-authentication-plugin=mysql_native_password --wait_timeout=864000
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_HOST: '%'
    networks:
      - default